# Generated by Django 2.2.2 on 2019-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='专线号')),
                ('area', models.CharField(max_length=8, verbose_name='地域标识')),
                ('month', models.DateField(verbose_name='当前月份')),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='计费金额')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='出账金额')),
                ('allowance_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='交叉补贴')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '收入异常列表',
                'verbose_name_plural': '收入异常列表',
            },
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=32, verbose_name='合同编码')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='合同金额')),
                ('contract_date', models.DateField(verbose_name='合同签订时间')),
                ('contract_expire', models.DateField(verbose_name='合同到期时间')),
                ('days', models.IntegerField(verbose_name='到期天数')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
                ('staff', models.CharField(max_length=8, verbose_name='客户经理')),
                ('group', models.CharField(max_length=8, verbose_name='支局(行客中心)')),
            ],
            options={
                'verbose_name': '合同到期预警',
                'verbose_name_plural': '合同到期预警',
            },
        ),
    ]
