# Generated by Django 2.2.2 on 2019-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal',
            name='group',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='支局(行客中心)'),
        ),
        migrations.AddField(
            model_name='abnormal',
            name='staff',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='expiration',
            name='group',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='支局(行客中心)'),
        ),
        migrations.AlterField(
            model_name='expiration',
            name='staff',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='客户经理'),
        ),
    ]
