# Generated by Django 2.2.2 on 2019-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '本地'), (1, '市级'), (2, '其他分公司'), (3, '集团一站'), (4, '测试')], default=0, verbose_name='地域标识'),
        ),
    ]
