# Generated by Django 2.2.2 on 2019-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_auto_20190911_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='bandwidth',
            field=models.PositiveIntegerField(max_length=16, verbose_name='套餐带宽'),
        ),
    ]
