# Generated by Django 2.2.2 on 2019-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_auto_20190911_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bandwidth',
            field=models.PositiveIntegerField(help_text='带宽单位为M', max_length=16, verbose_name='带宽(M)'),
        ),
    ]
