# Generated by Django 2.2.2 on 2019-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_auto_20190911_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bandwidth',
            field=models.PositiveIntegerField(help_text='带宽单位为M', verbose_name='带宽(M)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='bandwidth',
            field=models.PositiveIntegerField(verbose_name='套餐带宽'),
        ),
    ]
